version: '3.8'
services:
    db:
        build: db
        ports: 
            - 5432:5432
        env_file: db/Docker.env.list
        volumes: 
            - "/var/lib/postgresql/data"
    api:
        build:
            context: backend
            target: api
        env_file: backend/api/Docker.env.list
        ports: 
            - 8000:8000
    frontend:
        build: frontend
        ports: 
            - 80:80