version: '3.8'
services:
    postgrest:
        image: postgrest/postgrest:v7.0.1
        ports: 
            - 3000:3000
        environment: 
            PGRST_DB_URI: postgres://seeries:RcJhCBt2CE2dz7#B@db:5432/seeries
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: seeries # TODO: Change to a read-only user
            PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    db:
        image: timescale/timescaledb:1.7.4-pg12
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_USER: seeries
            POSTGRES_PASSWORD: RcJhCBt2CE2dz7#B
            POSTGRES_DB: seeries
        volumes: 
            - "/var/lib/postgresql/data"
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            API_URL: http://localhost:3000/
