FROM node:15.5-alpine
WORKDIR /app

# Copy npm install bits first as we want to cache that layer separately
COPY package.json package-lock.json tsconfig.base.json ./
RUN npm ci

COPY api/package.json package-lock.json api/

RUN cd api && npm ci

COPY api/src api/tsconfig.json api/

RUN cd api && npm run build

CMD [ "node", "api/build/index.js" ]